version: '2.4'
services:
  webapp:
    build:
      context: .
      target: 'webapp'
      dockerfile: Dockerfile
    env_file: .env
    container_name: webapp
    restart: unless-stopped
    ports:
      - 127.0.0.1:$APP_PORT:$APP_PORT
    environment:
      PORT: $APP_PORT

  certbot:
    image: certbot/certbot
    container_name: certbot
    env_file: .env
    volumes:
      - certbot-webroot:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - webserver
    command: certonly \
        --webroot --webroot-path=/var/www/html \
        --text \
        --email $LETSENCRYPT_EMAIL \
        --agree-tos \
        --no-eff-email \
        --preferred-challenges http-01 \
        --server https://acme-v02.api.letsencrypt.org/directory \
        --renew-by-default \
        -d $DOMAIN

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-webroot:/var/www/html
      - ./nginx.conf.templae:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: |
      envsubst < /etc/nginx/conf.d/nginx.conf.templae > /etc/nginx/conf.d/default.conf
    depends_on:
      - webapp

volumes:
  certbot-etc:
  certbot-var:
  certbot-webroot:
